# Netlify configuration for OpenRouter ImageGen MCP landing page
# This configuration publishes the website directory to Netlify

[build]
  # Directory to publish
  publish = "website"

  # No build command needed for static site
  command = "npm run website:validate"

# Redirects and rewrites
[[redirects]]
  # Redirect www to non-www
  from = "https://www.imageroutermcp.com/*"
  to = "https://imageroutermcp.com/:splat"
  status = 301
  force = true

[[redirects]]
  # Redirect GitHub link
  from = "/github"
  to = "https://github.com/scotthooker/OpenRouter-ImageGen-MCP"
  status = 302

[[redirects]]
  # Redirect docs link to README
  from = "/docs"
  to = "https://github.com/scotthooker/OpenRouter-ImageGen-MCP#readme"
  status = 302

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

    # Cache control for HTML
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/styles.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/script.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Custom 404 page (optional)
# [[redirects]]
#   from = "/*"
#   to = "/404.html"
#   status = 404
