blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/scotthooker/OpenRouter-ImageGen-MCP/discussions
    about: Ask questions or discuss ideas with the community
  - name: Documentation
    url: https://imageroutermcp.com
    about: Visit our documentation website
  - name: OpenRouter Support
    url: https://openrouter.ai/
    about: For issues specific to OpenRouter API
